---
- name: Configure OSPF on Cisco IOS routers loopback0
  hosts: routers
  gather_facts: no
  connection: network_cli

  vars:
    ospf_process_id: 1
    ospf_area: 0

  tasks:
    - name: Enable OSPF on loopback0
      cisco.ios.ios_config:
        lines:
          - ip ospf {{ ospf_process_id }} area {{ ospf_area }}
        parents: interface Loopback0